# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 07:39
from __future__ import unicode_literals

import cassupload.models
import cassupload.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, unique=True)),
                ('file', models.FileField(upload_to=cassupload.models.upl_to, validators=[cassupload.validators.validate_extension, cassupload.validators.validate_size])),
                ('play_count', models.IntegerField(default=0)),
                ('loud', models.BooleanField(default=False)),
            ],
        ),
    ]
